### ISSUE TITLE
PsGet install by Chocoatey or by One-liner?

### ISSUE THREAD

**Issue by AnneTheAgile** [psget/psget#167]
The docs recommend a one-liner to install [1] but I notice it has two package installers on chocolatey as well. So questions are; 

[]Are the two [2] [3] packages actually identical despite having different names? should the older one be removed?

[]I prefer using package management, even for package managers :). So if I use the [3] chocolatey, is that approved, and the only thing I'm missing is any changes that are in the repo but not yet packaged? I'm thinking that later, when Win10 comes with Chocolatey I'll already have a head start on my configuration management.
thank you! AnneTheAgile

1.[] ; ;Official docs ; ; ; X.PsGet - PowerShell Modules Directory - Get started ; ; http://psget.net/
````
(new-object Net.WebClient).DownloadString("http://psget.net/GetPsGet.ps1") | iex
````
2.[] ;Older ; ; ; ; X.Chocolatey Gallery | PsGet 1.0.3 ; ; https://chocolatey.org/packages/PsGet/1.0.3
3.[] ; Newer; ; ; ; X.Chocolatey Gallery | PsGet Utils 1.0.4.310 ; ; https://chocolatey.org/packages/PsGet

4.[] Posh-git was the reason I heard about psget; ; It is A PowerShell environment for Git that includes prompt setting and aliases for tab-completion. http://dahlbyk.github.io/posh-git/ ; ; ; X.dahlbyk/posh-git ; ; https://github.com/dahlbyk/posh-git
5.[] ;Posh-git enables profiles like this, a la a DotFiles example ; ; ; ; X.posh-git/profile.example.ps1 at master · dahlbyk/posh-git ; ; https://github.com/dahlbyk/posh-git/blob/master/profile.example.ps1

**Comment by flofreud** [comment]
Both packages on chocolatey are outdated. I didn't looked which changes the installation routines are missing but my recommendation would be to install via [1] to be able to use the latest version.

Probably you could take over the chocolatey package maintainance and update at least one feed?

Regarding Win10: it could be that PsGet will be obsolete because of https://github.com/oneget/oneget which will come with an PowerShell module provider.

**Comment by AnneTheAgile** [comment]
thank you @flofreud for such a quick and thorough answer! I'm  at the beginning stages of windows package management so I won't volunteer yet to do choloatey but it could be! I will keep it as a thought.
