### ISSUE TITLE
Sharing code amongst modules

### ISSUE THREAD

**Issue by eddiesholl** [psget/psget#179]
Hi all,

I'm diving into creating a set of powershell modules, which I'm hoping to pack and publish locally, to be installed via psget from a local network share. I'm struggling with a nice solution for sharing code amongst those modules. In particular the lack of dependency support in psget seems to be one of the limiting factors [issue 34](https://github.com/psget/psget/issues/34).

I'm wondering if there's 'psget friendly' way to achieve this, including just bundling copies of shared ps1 files in each seperate module zip. I've written up more details in a [stackoverflow post] (http://stackoverflow.com/questions/29665731/managing-shared-code-amongst-powershell-modules).

Any ideas would be much appreciated. Thanks,

Eddie

**Comment by flofreud** [comment]
The primary point not solved after reading your stackoverflow post is the dependency management between modules by PsGet which is a documented as feature request in #34. Therefore I will close this issue as duplicate.

Your solution in https://github.com/eddiesholl/posh-module-builder is really interesting. Sorry for this late responds.
