### ISSUE TITLE
Update psget to support NuGet v2 feeds

### ISSUE THREAD

**Issue by tillig** [psget/psget#182]
[The current OData query to get NuGet packages](https://github.com/psget/psget/blob/a248539ac55d7f4aa6d8b42c88fbca7895a9b6e6/PsGet/PsGet.psm1#L1913) appears to be for v1 protocol feeds.

    $Url = "{1}Packages()?`$filter=tolower(Id)+eq+'{0}'&`$orderby=Id" -f $NuGetPackageId.ToLower(), $Source

With newer feeds that use the v2 protocol, this fails. Products like ProGet haven't supported v1 feeds for a while.

NuGet v2 feeds expect the filter portion to be inside the `Packages()` method and IDs are already treated as case-insensitive, like this:

    $Url = "{1}Packages(Id='{0}')?`$orderby=Id" -f $NuGetPackageId, $Source

If you watch how `nuget.exe` queries NuGet on the wire, this is what you'll see.

I would be happy to provide a pull request with this if you're interested in updating.

**Comment by chaliy** [comment]
Sure, I will happily merge PR.
