### ISSUE TITLE
Unable to install modules from MyGet

### ISSUE THREAD

**Issue by russellseymour** [psget/psget#184]
I have recently configured the build of a module using MyGet, the resulting package being published in their NuGet feed.

On a new machine, with the latest version of PSGet installed I attempt the following command:

    Install-Module -NugetPackageId Logging -NugetSource https://www.myget.org/F/poshchef/api/v2

I get the following error from PowerShell:

![image](https://cloud.githubusercontent.com/assets/791658/8252392/8168cce2-167d-11e5-9069-d11b02004c7b.png)

Using Fiddler the Get request and error message is:
```
GET /F/poshchef/api/v2/Packages(Id='Logging')?$orderby=Id HTTP/1.1

HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Length: 299
Content-Type: application/xml;charset=utf-8
Server: Microsoft-IIS/8.5
X-Content-Type-Options: nosniff
DataServiceVersion: 1.0;
X-AspNet-Version: 4.0.30319
Set-Cookie: ai_session=40fd291eaa6a4cce8774702061f58941|2015-06-19T11:12:44.9463049+00:00|2015-06-19T11:12:45.0408251+00:00; expires=Fri, 19-Jun-2015 11:42:45 GMT; path=/
Set-Cookie: ai_user=edcbcdff8ae5450ea6e8a67adeac35a3|2015-06-19T11:12:44.9463049+00:00; expires=Fri, 31-Dec-9999 23:59:59 GMT; path=/
Date: Fri, 19 Jun 2015 11:12:44 GMT

<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code /><m:message xml:lang="en-US">The number of keys specified in the URI does not match number of key properties for the resource 'MyGet.V2FeedPackage'.</m:message></m:error>
```

**However** if I attempt the same command on a machine with an older version of PSGet installed, the installation of the module works.  The relevant GETs using fiddler are shown below:

    GET /F/poshchef/api/v2/Packages()?$filter=tolower(Id)+eq+'logging'&$orderby=Id HTTP/1.1
    GET /F/poshchef/api/v2/package/Logging/1.0.0.2 HTTP/1.1

I assume this is down to PSGet now supporting v2 feeds.  Does this mean that MyGet does not support v2 feeds or is this an issue with PSGet?

Thanks, Russell

**Comment by maartenba** [comment]
For a v2 feed it should actually hit /api/v2/FindPackagesById()?Id='Logging'

The generated url above looks wrong, as OData feeds typically require id and version in the request, e.g. /api/v2/Packages(Id=...,Version=....)
