### ISSUE TITLE
Long-term plans for PsGet?

### ISSUE THREAD

**Issue by mattheyan** [psget/psget#220]
Hi,

It was mentioned in issue #138 that PsGet is made obsolete by PowerShellGet and OneGet. I was wondering if you have long-term plans for PsGet or are you planning on phasing it out in favor of PowerShellGet?

Thanks,
Bryan

**Comment by chaliy** [comment]
Personally I do not have any plans. But there are many other contributors, who might have some plans. What I think is important for me and what I have find some time to do, is to add notifications to the main page, add uninstall instructions just in case and probably few items to the FAQ when people have problems due naming conflicts.

**Comment by flofreud** [comment]
My current plan is to keep PsGet functional for people who are using it and looking on the traffic shards there seems to be a demand. 

If there are shortcomings of PsGet compared to PowerShellGet we probably should start to recommend for new users to use the later but I didn't looked into it. If there are such, we could start to discuss this issue.

**Comment by mattheyan** [comment]
@flofreud - I think you have the right idea to keep it working for users. :)  @chaliy - It sounds like you have the same goals with documentation and FAQ. I imagine there are many people using PsGet today that you have to consider.

As far as PowerShellGet, that's where things get tricky because they are so similar... I think you should see it as validating that PowerShellGet is so similar. It means you did something right. :)

But, it also begs the question of what to do now. Here are a few things to consider.

* There is a naming conflict with `Install-Module`, which @chaliy mentioned. You don't have to worry about this for most users who are already using PsGet, but it presents a problem for some new users as well as those who may want to also use PowerShellGet.
* PowerShellGet is from Microsoft and is included with new versions of Windows, so adoption will naturally increase. This means that PsGet may not be able to compete with PowerShellGet in the long term, though I do not think that is your intention. It would be better if the two projects could work in harmony. :)
* There is a separate [PowerShell gallery](http://www.powershellgallery.com/items?itemType=PSModule) and [PsGet directory](http://psget.net/directory). Ideally people could start focusing their efforts to get the most benefit.
* For those users who do not have PowerShellGet already, it seems that PsGet is easier to set up, either using Chocolatey or 'GetPsGet.ps1'. PsGet is also portable, whereas PowerShellGet is definitely not, so I think there are still situations where someone would favor PsGet.

I realize that you don't know me and this may seem like it is coming out of nowhere, but I have been thinking about this a lot lately. Basically, I think it would be great if the direction of PsGet could shift towards helping people migrate to PowerShellGet in many cases, provide additional value on top of PowerShellGet moving forward, and act as a nearly identical alternative in cases where using PowerShellGet is not practical. I have many other ideas, but I am an outsider having only used PsGet to date, so I don't want to presume that any of this should be done, its up to you. I would like to get your thoughts and impressions first.

And I am able and ready to contribute code to the project if needed. But I would only be able to do that if the project's direction fit with the needs of my work, which is why I'm bringing this up now.

Also, I realize that there are already three different countries represented in this thread, so please let me know if something that I have said is unclear. ;)

Thanks,
Bryan
